/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrestadorLoginRouteImport } from './routes/prestador.login'
import { Route as PainelPrestadorRouteImport } from './routes/painel.prestador'
import { Route as CadastroPrestadorRouteImport } from './routes/cadastro.prestador'
import { Route as CadastroClienteRouteImport } from './routes/cadastro.cliente'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadorLoginRoute = PrestadorLoginRouteImport.update({
  id: '/prestador/login',
  path: '/prestador/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPrestadorRoute = PainelPrestadorRouteImport.update({
  id: '/painel/prestador',
  path: '/painel/prestador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroPrestadorRoute = CadastroPrestadorRouteImport.update({
  id: '/prestador',
  path: '/prestador',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroClienteRoute = CadastroClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => CadastroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/cadastro/cliente': typeof CadastroClienteRoute
  '/cadastro/prestador': typeof CadastroPrestadorRoute
  '/painel/prestador': typeof PainelPrestadorRoute
  '/prestador/login': typeof PrestadorLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/cadastro/cliente': typeof CadastroClienteRoute
  '/cadastro/prestador': typeof CadastroPrestadorRoute
  '/painel/prestador': typeof PainelPrestadorRoute
  '/prestador/login': typeof PrestadorLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/cadastro/cliente': typeof CadastroClienteRoute
  '/cadastro/prestador': typeof CadastroPrestadorRoute
  '/painel/prestador': typeof PainelPrestadorRoute
  '/prestador/login': typeof PrestadorLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/servicos'
    | '/cadastro/cliente'
    | '/cadastro/prestador'
    | '/painel/prestador'
    | '/prestador/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/servicos'
    | '/cadastro/cliente'
    | '/cadastro/prestador'
    | '/painel/prestador'
    | '/prestador/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/servicos'
    | '/cadastro/cliente'
    | '/cadastro/prestador'
    | '/painel/prestador'
    | '/prestador/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRouteWithChildren
  ServicosRoute: typeof ServicosRoute
  PainelPrestadorRoute: typeof PainelPrestadorRoute
  PrestadorLoginRoute: typeof PrestadorLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestador/login': {
      id: '/prestador/login'
      path: '/prestador/login'
      fullPath: '/prestador/login'
      preLoaderRoute: typeof PrestadorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/prestador': {
      id: '/painel/prestador'
      path: '/painel/prestador'
      fullPath: '/painel/prestador'
      preLoaderRoute: typeof PainelPrestadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/prestador': {
      id: '/cadastro/prestador'
      path: '/prestador'
      fullPath: '/cadastro/prestador'
      preLoaderRoute: typeof CadastroPrestadorRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/cliente': {
      id: '/cadastro/cliente'
      path: '/cliente'
      fullPath: '/cadastro/cliente'
      preLoaderRoute: typeof CadastroClienteRouteImport
      parentRoute: typeof CadastroRoute
    }
  }
}

interface CadastroRouteChildren {
  CadastroClienteRoute: typeof CadastroClienteRoute
  CadastroPrestadorRoute: typeof CadastroPrestadorRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroClienteRoute: CadastroClienteRoute,
  CadastroPrestadorRoute: CadastroPrestadorRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRouteWithChildren,
  ServicosRoute: ServicosRoute,
  PainelPrestadorRoute: PainelPrestadorRoute,
  PrestadorLoginRoute: PrestadorLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
